const ORIGIN='https://muniverse-official.github.io',TTL=900000,REV='20260909-stateless-v8';type O=Record<string,any>;class Err extends Error{constructor(public code:string,public status=400){super(code)}}
function H(r:Request,status=200){const h:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type,x-music-core-request,x-cover-pick-request,x-request-id','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Attendee-Revision':REV};if(r.headers.get('origin')===ORIGIN)h['Access-Control-Allow-Origin']=ORIGIN;if(status===429)h['Retry-After']='3';if(status===503)h['Retry-After']='2';return h}function J(r:Request,x:O,s=200){return new Response(JSON.stringify({...x,serverTime:new Date().toISOString()}),{status:s,headers:H(r,s)})}
function C(v:any,m=300){return String(v??'').normalize('NFKC').trim().slice(0,m)}const E=(v:any)=>C(v,254).toLowerCase(),N=(v:any)=>C(v,80).replace(/\s+/g,' '),VE=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);function VD(v:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v}
function svc(){const base=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!base||!key)throw new Err('SERVER_BUSY',503);return{base,key}}
async function S(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))),x=>x.toString(16).padStart(2,'0')).join('')}
async function rpc(name:string,body:O){const{base,key}=svc();const r=await fetch(`${base}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(8000)});const t=await r.text();if(!r.ok)throw new Err('SERVER_BUSY',503);try{return JSON.parse(t)}catch{throw new Err('SERVER_BUSY',503)}}
async function fingerprint(r:Request){const ip=(r.headers.get('cf-connecting-ip')||r.headers.get('x-real-ip')||(r.headers.get('x-forwarded-for')||'').split(',').at(-1)||'unknown').trim(),ua=C(r.headers.get('user-agent'),500),salt=Deno.env.get('RATE_LIMIT_SALT')||svc().key;return{ip:await S(salt+':ip:'+ip),ua:await S(salt+':ua:'+ua)}}
function status(code:string){if(code==='ALREADY_SUBMITTED')return 409;if(['WINNER_MISMATCH','IDENTITY_MISMATCH','WINNER_PARTIAL_MISMATCH','WINNER_NOT_LISTED'].includes(code))return 404;if(code==='SESSION_INVALID')return 401;if(code==='TOO_MANY_ATTEMPTS')return 429;if(code==='CLOSED')return 410;if(code==='NOT_OPEN')return 425;if(code==='PAUSED')return 423;if(['UNDER_15','INVALID_FIELDS','MISSING_FIELDS','CONSENT_REQUIRED','INVALID_X_ACCOUNT'].includes(code))return 400;return 503}
function X(v:any){let x=C(v,100).replace(/^https?:\/\/(?:(?:www|mobile)\.)?(?:x\.com|twitter\.com)\//i,'').split(/[/?#]/)[0].replace(/^@+/,'');if(!/^[A-Za-z0-9_]{1,15}$/.test(x))throw new Err('INVALID_X_ACCOUNT');return'@'+x}
function b64u(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function from64(s:string){if(!/^[A-Za-z0-9_-]+$/.test(s))throw new Err('SESSION_INVALID',401);const p=s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4);let raw='';try{raw=atob(p)}catch{throw new Err('SESSION_INVALID',401)}return Uint8Array.from(raw,c=>c.charCodeAt(0))}
let keyPromise:Promise<CryptoKey>|null=null;async function signingKey(){if(!keyPromise){keyPromise=(async()=>{const seed=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('attendee-stateless-v1:'+svc().key));return crypto.subtle.importKey('raw',seed,{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])})()}return keyPromise}
async function issue(claims:O){const payload=b64u(new TextEncoder().encode(JSON.stringify(claims))),sig=new Uint8Array(await crypto.subtle.sign('HMAC',await signingKey(),new TextEncoder().encode(payload)));return payload+'.'+b64u(sig)}
async function parse(raw:string){const parts=raw.split('.');if(parts.length!==2)throw new Err('SESSION_INVALID',401);const[payload,sig]=parts,ok=await crypto.subtle.verify('HMAC',await signingKey(),from64(sig),new TextEncoder().encode(payload));if(!ok)throw new Err('SESSION_INVALID',401);let x:O;try{x=JSON.parse(new TextDecoder().decode(from64(payload)))}catch{throw new Err('SESSION_INVALID',401)}if(x?.v!==1||typeof x.p!=='string'||typeof x.w!=='string'||typeof x.r!=='string'||typeof x.i!=='string'||typeof x.ip!=='string'||typeof x.ua!=='string'||!Number.isFinite(x.exp)||Date.now()>x.exp)throw new Err('SESSION_INVALID',401);return x}
async function verify(r:Request,p:string,b:O,f:O){const e=E(b.email),n=N(b.nickname);if(!VE(e)||!n)throw new Err('MISSING_FIELDS');const normalized=p==='fans_pick'?n.toLowerCase():n,ih=await S(e+'\n'+normalized),out=await rpc('attendee_check_winner',{p_program:p,p_identity_hash:ih,p_email_hash:await S(e),p_nickname_hash:await S(normalized),p_rate_identity:await S(f.ip+':'+f.ua+':'+ih),p_rate_fingerprint:await S(f.ip+':'+f.ua)});if(!out?.ok)throw new Err(out?.code||'SERVER_BUSY',status(out?.code||''));const exp=Date.now()+TTL,t=await issue({v:1,p,w:out.winner_id,r:out.round_id,i:ih,ip:f.ip,ua:f.ua,exp});return J(r,{ok:true,token:t,verificationToken:t,expiresAt:new Date(exp).toISOString(),roundId:out.round_id,eventDate:out.event_date,eventDateTba:out.event_date_tba===true,showEventDate:out.show_event_date===true})}
async function submit(r:Request,p:string,b:O,f:O){const raw=C(b.verification_token||b.token,4096);if(!raw)throw new Err('SESSION_INVALID',401);const claims=await parse(raw);if(claims.p!==p||claims.ip!==f.ip||claims.ua!==f.ua)throw new Err('SESSION_INVALID',401);const email=E(b.account_email),nick=N(b.muniverse_nickname),normalized=p==='fans_pick'?nick.toLowerCase():nick;if(!VE(email)||!nick||await S(email+'\n'+normalized)!==claims.i)throw new Err('SESSION_INVALID',401);const name=C(b.name,100),nat=C(b.nationality,2).toUpperCase(),birth=C(b.birth_date,10),phone=C(b.phone,40),contact=E(b.contact_email);if(!name||!nat||!birth||!phone||!contact)throw new Err('MISSING_FIELDS');if(!/^[A-Z]{2}$/.test(nat)||!VD(birth)||!(/^010-\d{4}-\d{4}$/.test(phone)||/^\+\d{8,15}$/.test(phone))||!VE(contact))throw new Err('INVALID_FIELDS');const x=X(b.x_account),out=await rpc('attendee_commit_registration',{p_program:p,p_winner_id:claims.w,p_identity_hash:claims.i,p_account_email:email,p_nickname:nick,p_name:name,p_nationality:nat,p_birth_date:birth,p_phone:phone,p_x_account:x,p_contact_email:contact,p_ip_hash:f.ip});if(!out?.ok)throw new Err(out?.code||'SERVER_BUSY',status(out?.code||''));return J(r,{ok:true,registered:true,roundId:out.round_id,eventDate:out.event_date,eventDateTba:out.event_date_tba===true,showEventDate:out.show_event_date===true,deliveryQueued:out.delivery_queued===true})}
Deno.serve(async r=>{if(r.headers.get('origin')!==ORIGIN)return J(r,{ok:false,code:'ORIGIN_DENIED'},403);if(r.method==='OPTIONS')return new Response(null,{status:204,headers:H(r)});const u=new URL(r.url),p=u.searchParams.get('program')||'',a=u.searchParams.get('action')||'';if(r.method==='GET'&&a==='clock'&&['music_core','fans_pick'].includes(p))return J(r,{ok:true});if(r.method!=='POST')return J(r,{ok:false},405);if(!['music_core','fans_pick'].includes(p)||!['verify','submit'].includes(a))return J(r,{ok:false},404);const reqHeader=p==='music_core'?'x-music-core-request':'x-cover-pick-request';if(r.headers.get(reqHeader)!=='1'||!r.headers.get('content-type')?.startsWith('application/json'))return J(r,{ok:false,code:'BAD_REQUEST'},400);try{const text=await r.text();if(new TextEncoder().encode(text).length>16384)throw new Err('PAYLOAD_TOO_LARGE',413);let b:O;try{b=JSON.parse(text)}catch{throw new Err('INVALID_JSON')}if(!b||Array.isArray(b)||typeof b!=='object')throw new Err('INVALID_JSON');if(b.privacy_consent!==true)throw new Err('CONSENT_REQUIRED');if(C(b.website))throw new Err(p==='fans_pick'?'IDENTITY_MISMATCH':'WINNER_NOT_LISTED',404);const f=await fingerprint(r);return a==='verify'?await verify(r,p,b,f):await submit(r,p,b,f)}catch(e){const x=e instanceof Err?e:new Err('SERVER_BUSY',503);return J(r,{ok:false,code:x.code},x.status)}});
