const ORIGIN='https://muniverse-official.github.io',REV='20260908-rounds-v5';type O=Record<string,any>;
class Err extends Error{constructor(public code:string,public status=400){super(code)}}
function H(r:Request){const h:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'authorization,content-type,x-admin-request','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Attendee-Revision':REV};if(r.headers.get('origin')===ORIGIN)h['Access-Control-Allow-Origin']=ORIGIN;return h}
function J(r:Request,b:O,s=200){return new Response(JSON.stringify(b),{status:s,headers:H(r)})}
function env(){const base=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!base||!key)throw new Err('SERVICE_UNAVAILABLE',503);return{base,key}}
async function DB(path:string,init:RequestInit={}){const{base,key}=env();const h=new Headers(init.headers);h.set('apikey',key);h.set('authorization',`Bearer ${key}`);if(init.body)h.set('content-type','application/json');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:h,signal:AbortSignal.timeout(20000)});const t=await r.text();if(!r.ok){let d:O={};try{d=JSON.parse(t)}catch{}if(d.code==='23505')throw new Err(String(d.message).includes('attendee_rounds')?'DUPLICATE_ROUND':'DUPLICATE_WINNER',409);for(const c of ['DELIVERY_IN_PROGRESS','DELIVERY_NOT_FOUND','DELIVERY_NOT_RETRYABLE','DELIVERY_REVIEW_REQUIRED','WINNER_NOT_FOUND','ROUND_NOT_FOUND','ROUND_REQUIRED','ROUND_CONFLICT','ROUND_ARCHIVED','ROUND_INCOMPLETE','PUBLIC_ROUND_CANNOT_ARCHIVE','ROUND_TITLE_REQUIRED','INVALID_WINDOW','INVALID_DATE','CONFIRM_REQUIRED'])if(String(d.message).includes(c))throw new Err(c,c.endsWith('NOT_FOUND')?404:409);throw new Err('DATABASE_ERROR',500)}return t?JSON.parse(t):null}
const post=(p:string,b:O)=>DB(p,{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify(b)}),rpc=(p:string,b:O)=>DB('rpc/'+p,{method:'POST',body:JSON.stringify(b)});
const hex=(b:Uint8Array)=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');async function S(v:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))))}const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
async function PH(p:string,s:string,i:number){if(!/^[0-9a-f]{64}$/.test(s)||i<100000||i>1000000)throw new Err('SERVICE_UNAVAILABLE',503);const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);return hex(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(s.match(/../g)!,x=>parseInt(x,16)),iterations:i,hash:'SHA-256'},k,256)))}
function eq(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function C(v:any,m:number){if(typeof v!=='string')throw new Err('INVALID_FIELDS');const s=v.normalize('NFKC').trim();if(s.length>m||/[\u0000-\u001f\u007f]/.test(s))throw new Err('INVALID_FIELDS');return s}
function D(v:any){const s=C(v,10),t=new Date(s+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(t.getTime())||t.toISOString().slice(0,10)!==s)throw new Err('INVALID_DATE');return s}
function T(v:any){const s=C(v,40);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?(?:Z|[+-]\d{2}:\d{2})$/.test(s)||!Number.isFinite(Date.parse(s)))throw new Err('INVALID_WINDOW');D(s.slice(0,10));return s}
function B(v:any){if(typeof v!=='boolean')throw new Err('INVALID_FIELDS');return v}function ID(v:any){const s=C(v,36);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s))throw new Err('INVALID_FIELDS');return s}
async function identity(p:string,x:O){const email=C(x.email,254).toLowerCase(),nickname=C(x.nickname,80).replace(/\s+/g,' ');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!nickname)throw new Err('INVALID_WINNER');const n=p==='fans_pick'?nickname.toLowerCase():nickname;return{email,nickname,identity_hash:await S(email+'\n'+n),email_hash:await S(email),nickname_hash:await S(n)}}
const account=async(u:string)=>(await DB(`attendee_console_accounts?username=eq.${encodeURIComponent(u)}&select=username,password_hash,password_salt,iterations,active,updated_at&limit=1`))?.[0];const throttle=(k:string,l:number,s:number)=>rpc('attendee_console_throttle',{p_key:k,p_limit:l,p_seconds:s});const audit=(u:string,a:string)=>post('attendee_console_audit',{username:u,action:a});
async function auth(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer /,'');if(!/^[0-9a-f]{64}$/.test(t))throw new Err('UNAUTHORIZED',401);const h=await S(t),s=(await DB(`attendee_console_sessions?token_hash=eq.${h}&select=token_hash,username,expires_at,created_at&limit=1`))?.[0];if(!s||Date.parse(s.expires_at)<=Date.now())throw new Err('SESSION_EXPIRED',401);const a=await account(s.username);if(!a?.active||Date.parse(a.updated_at)>Date.parse(s.created_at))throw new Err('SESSION_EXPIRED',401);return{...s,account:a}}
Deno.serve(async r=>{if(r.method==='GET')return J(r,{ok:true,revision:REV});if(r.headers.get('origin')!==ORIGIN)return J(r,{ok:false,code:'ORIGIN_DENIED'},403);if(r.method==='OPTIONS')return new Response(null,{status:204,headers:H(r)});if(r.method!=='POST')return J(r,{ok:false,code:'METHOD_NOT_ALLOWED'},405);if(r.headers.get('x-admin-request')!=='1'||!r.headers.get('content-type')?.startsWith('application/json'))return J(r,{ok:false,code:'INVALID_REQUEST'},400);
try{const text=await r.text();if(new TextEncoder().encode(text).length>131072)throw new Err('PAYLOAD_TOO_LARGE',413);let b:O;try{b=JSON.parse(text)}catch{throw new Err('INVALID_JSON')}if(!b||Array.isArray(b)||typeof b!=='object')throw new Err('INVALID_JSON');
if(b.action==='login'){const u=C(b.username,40).toLowerCase();if(typeof b.password!=='string'||b.password.length>256)throw new Err('INVALID_CREDENTIALS',401);const ip=(r.headers.get('cf-connecting-ip')||r.headers.get('x-real-ip')||(r.headers.get('x-forwarded-for')||'unknown').split(',').at(-1)||'unknown').trim();if(!await throttle(await S(env().key+':console-login:'+ip),12,600)||!await throttle('console-login-global',120,600))throw new Err('RATE_LIMITED',429);const a=await account(u),h=await PH(b.password,a?.password_salt||'0'.repeat(64),a?.iterations||600000);if(!a?.active||!eq(h,a.password_hash)){await new Promise(r=>setTimeout(r,250));throw new Err('INVALID_CREDENTIALS',401)}const token=random(),expiresAt=new Date(Date.now()+7200000).toISOString();await post('attendee_console_sessions',{token_hash:await S(token),username:u,expires_at:expiresAt});await audit(u,'login');return J(r,{ok:true,token,expiresAt,username:u,revision:REV})}
const s=await auth(r);if(!await throttle('console-session:'+s.token_hash,180,60))throw new Err('RATE_LIMITED',429);
if(b.action==='logout'){await DB(`attendee_console_sessions?token_hash=eq.${s.token_hash}`,{method:'DELETE'});return J(r,{ok:true})}
if(b.action==='get'){const[music_core,fans_pick,history,delivery]=await Promise.all([rpc('attendee_round_data',{p_program:'music_core'}),rpc('attendee_round_data',{p_program:'fans_pick'}),DB('attendee_console_audit?select=id,username,program,action,detail,created_at&order=id.desc&limit=60'),rpc('attendee_delivery_console',{})]);return J(r,{ok:true,username:s.username,expiresAt:s.expires_at,music_core,fans_pick,history,delivery,serverTime:new Date().toISOString(),revision:REV})}
if(b.action==='change_password'){if(!await throttle('console-password:'+s.username,5,600))throw new Err('RATE_LIMITED',429);if(typeof b.current_password!=='string'||typeof b.new_password!=='string'||b.new_password.length<12||b.new_password.length>128)throw new Err('PASSWORD_LENGTH');if(!eq(await PH(b.current_password,s.account.password_salt,s.account.iterations),s.account.password_hash))throw new Err('INVALID_CREDENTIALS',400);const salt=random();await DB(`attendee_console_accounts?username=eq.${encodeURIComponent(s.username)}`,{method:'PATCH',body:JSON.stringify({password_hash:await PH(b.new_password,salt,600000),password_salt:salt,iterations:600000,updated_at:new Date().toISOString()})});await DB(`attendee_console_sessions?username=eq.${encodeURIComponent(s.username)}`,{method:'DELETE'});await audit(s.username,'change_password');return J(r,{ok:true,relogin:true})}
const p=b.program;if(!['music_core','fans_pick'].includes(p))throw new Err('INVALID_PROGRAM');let data:O={};
if(b.action==='retry_delivery'){if(!Number.isSafeInteger(b.id)||b.id<1)throw new Err('INVALID_FIELDS');const out=await rpc('attendee_delivery_retry',{p_program:p,p_round_id:ID(b.round_id),p_id:b.id,p_username:s.username});return J(r,{...out,ok:true})}

if(b.action==='create_round'){const title=C(b.title,120);if(!title)throw new Err('ROUND_TITLE_REQUIRED');data={title};if(b.source_round_id)data.source_round_id=ID(b.source_round_id)}
else{if(!b.round_id)throw new Err('ROUND_REQUIRED',409);data.round_id=ID(b.round_id);
if(['save_config','publish_round','archive_round','restore_round'].includes(b.action)){if(!Number.isInteger(b.expected_version)||b.expected_version<1)throw new Err('ROUND_CONFLICT',409);data.expected_version=b.expected_version}
if(b.action==='save_config'){const title=C(b.title,120),t=B(b.event_date_tba),o=b.registration_open_at?T(b.registration_open_at):'',c=b.registration_close_at?T(b.registration_close_at):'';if(!title)throw new Err('ROUND_TITLE_REQUIRED');if(Boolean(o)!==Boolean(c)||(o&&Date.parse(o)>=Date.parse(c)))throw new Err('INVALID_WINDOW');Object.assign(data,{title,event_date:t?'':D(b.event_date),event_date_tba:t,registration_open_at:o,registration_close_at:c,show_event_date:B(b.show_event_date),test_mode:B(b.test_mode),registration_paused:B(b.registration_paused)})}
else if(b.action==='add_winners'){if(!Array.isArray(b.winners)||!b.winners.length||b.winners.length>500)throw new Err('WINNER_LIMIT');data.winners=[];for(const x of b.winners){if(!x||typeof x!=='object')throw new Err('INVALID_WINNER');data.winners.push(await identity(p,x))}}
else if(b.action==='update_winner')Object.assign(data,{id:ID(b.id),...await identity(p,b)});
else if(b.action==='delete_winner'){if(b.confirm_delete!==true)throw new Err('CONFIRM_REQUIRED');Object.assign(data,{id:ID(b.id),confirm_delete:true})}
else if(['publish_round','archive_round','restore_round'].includes(b.action)){if(b.confirm!==true)throw new Err('CONFIRM_REQUIRED')}
else throw new Err('UNKNOWN_ACTION',404)}
const out=await rpc('attendee_round_mutate',{p_program:p,p_action:b.action,p_data:data,p_username:s.username});let configPublished:null|boolean=null;if(['save_config','publish_round'].includes(b.action)){configPublished=false;try{const secrets=await DB('attendee_internal_secrets?name=eq.config_sync&select=secret&limit=1');const sync=await fetch(env().base+'/functions/v1/attendee-config-sync',{method:'POST',headers:{'x-sync-secret':secrets?.[0]?.secret||''},signal:AbortSignal.timeout(10000)});configPublished=sync.ok&&(await sync.json()).ok===true}catch{}}return J(r,{...out,ok:true,configPublished});
}catch(e){const x=e instanceof Err?e:new Err('SERVER_ERROR',500);return J(r,{ok:false,code:x.code},x.status)}});
