
CREATE OR REPLACE FUNCTION pg_temp.attendee_qa_20260908() RETURNS jsonb LANGUAGE plpgsql AS $qa$
DECLARE p text; rid uuid; other uuid; wid uuid; v integer; c jsonb; data jsonb; out jsonb; cases jsonb='[]'; h text; em text; ni text; oid bigint; n integer; code text; before_counts jsonb; after_counts jsonb;
BEGIN
 SELECT jsonb_build_object('rounds',(select count(*) from attendee_rounds),'mw',(select count(*) from music_core_winners),'fw',(select count(*) from cover_pick_winners),'ma',(select count(*) from music_core_attendees),'fa',(select count(*) from cover_pick_attendees),'outbox',(select count(*) from attendee_delivery_outbox)) INTO before_counts;
 BEGIN
  FOREACH p IN ARRAY ARRAY['music_core','fans_pick'] LOOP
   em='qa-20260908@example.invalid';ni='QA-20260908';if p='fans_pick' then ni=lower(ni);end if;
   h=encode(extensions.digest(em||E'\n'||ni,'sha256'),'hex');
   data=attendee_round_mutate(p,'create_round',jsonb_build_object('title','QA-ROLLBACK-'||p||'-'||gen_random_uuid()),'QA_ROLLBACK');
   rid=(data->>'round_id')::uuid;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','create_unpublished_round','pass',(select not is_public from attendee_rounds where id=rid)));
   BEGIN
    perform attendee_round_mutate(p,'publish_round',jsonb_build_object('round_id',rid,'expected_version',1),'QA_ROLLBACK');
    code='UNEXPECTED_SUCCESS';
   EXCEPTION WHEN OTHERS THEN code=SQLERRM; END;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','reject_publish_missing_window','pass',code='ROUND_INCOMPLETE','actual',code));
   c=jsonb_build_object('round_id',rid,'title',(select title from attendee_rounds where id=rid),'expected_version',1,'event_date','2026-09-12','event_date_tba',false,'registration_open_at','2026-09-01T00:00:00+09:00','registration_close_at','2026-09-30T23:59:59+09:00','show_event_date',true,'test_mode',false,'registration_paused',false);
   perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');
   perform attendee_round_mutate(p,'publish_round',jsonb_build_object('round_id',rid,'expected_version',2),'QA_ROLLBACK');
   select version into v from attendee_rounds where id=rid;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','one_public_round','pass',(select count(*)=1 from attendee_rounds where program=p and is_public)));
   data=jsonb_build_object('round_id',rid,'winners',jsonb_build_array(jsonb_build_object('email',em,'nickname',ni,'identity_hash',h,'email_hash',encode(extensions.digest(em,'sha256'),'hex'),'nickname_hash',encode(extensions.digest(ni,'sha256'),'hex'))));
   out=attendee_round_mutate(p,'add_winners',data,'QA_ROLLBACK');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','add_winner','pass',out->>'added'='1'));
   out=attendee_round_mutate(p,'add_winners',data,'QA_ROLLBACK');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','deduplicate_winner','pass',out->>'added'='0' and out->>'duplicates'='1'));
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   wid=(out->>'winner_id')::uuid;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','verify_current_round','pass',out->>'ok'='true' and out->>'round_id'=rid::text));
   for n in 1..13 loop out=attendee_check_winner(p,repeat('0',64),repeat('0',64),repeat('0',64),'qa-invalid-identity','qa-invalid-fingerprint');end loop;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','failed_identity_rate_limit','pass',out->>'code'='TOO_MANY_ATTEMPTS'));
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-invalid-identity','qa-invalid-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','valid_winner_not_blocked_by_failed_lookup_bucket','pass',out->>'ok'='true'));
   out=attendee_commit_registration(p,wid,h,em,ni,'QA', 'KR',date '2015-01-01','010-1234-5678','@qa_test',em,'qa-ip');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','reject_under15','pass',out->>'code'='UNDER_15'));
   out=attendee_commit_registration(p,wid,h,em,ni,'QA', 'KR',date '2000-01-01','invalid','@qa_test',em,'qa-ip');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','reject_invalid_phone','pass',out->>'code'='INVALID_FIELDS'));
   c=c||jsonb_build_object('expected_version',v,'registration_paused',true);perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');v=v+1;
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','pause_server_verify','pass',out->>'code'='PAUSED'));
   out=attendee_commit_registration(p,wid,h,em,ni,'QA','KR',date '2000-01-01','010-1234-5678','@qa_test',em,'qa-ip');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','pause_server_submit','pass',out->>'code'='PAUSED'));
   c=c||jsonb_build_object('expected_version',v,'registration_paused',false,'registration_open_at','2026-09-09T17:00:00+09:00');perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');v=v+1;
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','not_open_server_verify','pass',out->>'code'='NOT_OPEN'));
   c=c||jsonb_build_object('expected_version',v,'test_mode',true);perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');v=v+1;
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','test_mode_before_start','pass',out->>'ok'='true'));
   c=c||jsonb_build_object('expected_version',v,'registration_open_at','2026-09-01T00:00:00+09:00','registration_close_at','2026-09-07T17:00:00+09:00');perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');v=v+1;
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','test_mode_obeys_close','pass',out->>'code'='CLOSED'));
   BEGIN perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');code='UNEXPECTED_SUCCESS';EXCEPTION WHEN OTHERS THEN code=SQLERRM;END;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','reject_stale_admin_version','pass',code='ROUND_CONFLICT','actual',code));
   c=c||jsonb_build_object('expected_version',v,'test_mode',false,'registration_close_at','2026-09-30T23:59:59+09:00');perform attendee_round_mutate(p,'save_config',c,'QA_ROLLBACK');v=v+1;
   out=attendee_commit_registration(p,wid,h,em,ni,'QA', 'KR',date '2000-01-01','010-1234-5678','@qa_test',em,'qa-ip');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','register_and_enqueue_atomically','pass',out->>'ok'='true' and (select count(*)=1 from attendee_delivery_outbox where program=p and winner_id=wid),'actual',out));
   out=attendee_commit_registration(p,wid,h,em,ni,'QA', 'KR',date '2000-01-01','010-1234-5678','@qa_test',em,'qa-ip');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','reject_duplicate_registration','pass',out->>'code'='ALREADY_SUBMITTED'));
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-identity','qa-fingerprint');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','registered_winner_status','pass',out->>'code'='ALREADY_SUBMITTED'));
   select id into oid from attendee_delivery_outbox where program=p and winner_id=wid;
   update attendee_delivery_outbox set status='processing',attempts=1,locked_at=now() where id=oid;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','delivery_authorizes_existing_winner','pass',attendee_delivery_is_current(oid)));
   BEGIN perform attendee_round_mutate(p,'delete_winner',jsonb_build_object('round_id',rid,'id',wid,'confirm_delete',true),'QA_ROLLBACK');code='UNEXPECTED_SUCCESS';EXCEPTION WHEN OTHERS THEN code=SQLERRM;END;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','delete_refuses_inflight_delivery','pass',code='DELIVERY_IN_PROGRESS','actual',code));
   perform attendee_delivery_finish(oid,false,true,false,'QA simulated email failure');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','persist_partial_sheet_success','pass',(select sheet_updated from attendee_delivery_outbox where id=oid),'actual',(select jsonb_build_object('status',status,'sheet_updated',sheet_updated,'email_sent',email_sent) from attendee_delivery_outbox where id=oid)));
   update attendee_delivery_outbox set status='processing',attempts=2,locked_at=now() where id=oid;
   perform attendee_delivery_finish(oid,false,false,false,'QA timeout');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','partial_success_is_monotonic','pass',(select sheet_updated from attendee_delivery_outbox where id=oid)));
   update attendee_delivery_outbox set status='failed',last_error='EMAIL_SEND_FAILED' where id=oid;
   perform attendee_delivery_retry(p,rid,oid,'QA_ROLLBACK');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','retry_keeps_partial_success','pass',(select status='pending' and sheet_updated and attempts=0 from attendee_delivery_outbox where id=oid)));
   update attendee_delivery_outbox set status='failed',last_error='HTTP_200:EMAIL_STATUS_UNCERTAIN' where id=oid;
   BEGIN perform attendee_delivery_retry(p,rid,oid,'QA_ROLLBACK');code='UNEXPECTED_SUCCESS';EXCEPTION WHEN OTHERS THEN code=SQLERRM;END;
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','uncertain_email_requires_review','pass',code='DELIVERY_REVIEW_REQUIRED'));
   perform attendee_round_mutate(p,'delete_winner',jsonb_build_object('round_id',rid,'id',wid,'confirm_delete',true),'QA_ROLLBACK');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','delete_clears_delivery_personal_data','pass',not exists(select 1 from attendee_delivery_outbox where program=p and winner_id=wid),'remaining_rows',(select count(*) from attendee_delivery_outbox where program=p and winner_id=wid)));
   data=attendee_round_mutate(p,'create_round',jsonb_build_object('title','QA-NEXT-'||p||'-'||gen_random_uuid(),'source_round_id',rid),'QA_ROLLBACK');other=(data->>'round_id')::uuid;
   perform attendee_round_mutate(p,'publish_round',jsonb_build_object('round_id',other,'expected_version',1),'QA_ROLLBACK');
   out=attendee_check_winner(p,h,encode(extensions.digest(em,'sha256'),'hex'),encode(extensions.digest(ni,'sha256'),'hex'),'qa-new-round','qa-new-round');
   cases=cases||jsonb_build_array(jsonb_build_object('program',p,'case','next_round_does_not_inherit_winners','pass',out->>'ok'='false'));
  END LOOP;
  RAISE EXCEPTION 'QA_ROLLBACK_COMPLETE';
 EXCEPTION WHEN OTHERS THEN
  if SQLERRM<>'QA_ROLLBACK_COMPLETE' then return jsonb_build_object('aborted',true,'error',SQLERRM,'cases',cases);end if;
 END;
 SELECT jsonb_build_object('rounds',(select count(*) from attendee_rounds),'mw',(select count(*) from music_core_winners),'fw',(select count(*) from cover_pick_winners),'ma',(select count(*) from music_core_attendees),'fa',(select count(*) from cover_pick_attendees),'outbox',(select count(*) from attendee_delivery_outbox)) INTO after_counts;
 RETURN jsonb_build_object('cases',cases,'rolled_back',before_counts=after_counts,'before',before_counts,'after',after_counts);
END $qa$;
SELECT pg_temp.attendee_qa_20260908() AS qa_results;
